name: deno-deploy
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            id-token: write # Needed for auth with Deno Deploy
            contents: read # Needed to clone the repository
        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                  run_install: false

            - uses: actions/setup-node@v3
              with:
                  node-version: 22
                  cache: pnpm

            - run: pnpm install

            - run: pnpm generate

            - uses: denoland/setup-deno@v2
              name: Set up Deno
              with:
                  deno-version: v2.x

            # Install the deployctl CLI tool
            - name: Install deployctl
              run: deno install --allow-read --allow-write --allow-env --allow-net --allow-run --no-check -rfg https://deno.land/x/deploy/deployctl.ts

            # Deploy using the CLI, providing only the project and the root directory
            - name: Deploy to Deno Deploy via CLI
              run: deployctl deploy --project=finxol-blog .output/public
